# Generated by Django 3.1 on 2020-10-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_address_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='company',
        ),
    ]
