# Generated by Django 3.1 on 2020-10-11 21:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201012_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
