# Generated by Django 3.1 on 2020-10-11 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201012_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
