# Generated by Django 2.2 on 2020-06-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
